# Generated by Django 6.0.2 on 2026-02-13 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bands', '0001_initial'),
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('tour_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concerts', to='bands.band')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SetlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('encore', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setlist', to='concerts.concert')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.song')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('concert', 'order')},
            },
        ),
    ]
