# Generated by Django 6.0.2 on 2026-02-13 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration', models.PositiveIntegerField(help_text='Duration in seconds')),
                ('lyrics_preview', models.TextField(blank=True)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='bands.band')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
