# Generated by Django 6.0.2 on 2026-02-20 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='release_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year the song was released.', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration in minutes'),
        ),
    ]
